name: Netplay V3 for Linux

on:
  push:
    branches: [ "bb" ]
  pull_request:
    branches: [ "bb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Create build directory and run CMake"
      run: cmake -S . -B build -G "Unix Makefiles" -DLINUX_LOCAL_DEV=true
    - name: "Build Project" 
      run: cmake --build build --target all --config Release -- -j$(nproc)
    - name: Run make
      run: make
    - name: Copy Files
      run: cp -r ../Data/Sys/ ../Data/User/ {{github.workspace}}/Binaries/
    - name: Make build portable
      run: touch {{github.workspace}}/Binaries/portable.txt
