name: Netplay V3 for Linux

on:
  push:
    branches: [ "bb" ]
  pull_request:
    branches: [ "bb" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Install prerequisites"
      shell: bash
      run: |
          sudo dpkg --add-architecture amd64
          sudo apt update
          sudo apt install \
          cmake \
          pkg-config \
          git \
          wget \
          libao-dev \
          libasound2-dev \
          libavcodec-dev \
          libavformat-dev \
          libbluetooth-dev \
          libenet-dev \
          libgtk2.0-dev \
          liblzo2-dev \
          libminiupnpc-dev \
          libopenal-dev \
          libpulse-dev \
          libreadline-dev \
          libsfml-dev \
          libsoil-dev \
          libsoundtouch-dev \
          libswscale-dev \
          libusb-1.0-0-dev \
          libwebkit2gtk-4.0-dev \
          libxext-dev \
          libxrandr-dev \
          portaudio19-dev \
          zlib1g-dev \
          libudev-dev \
          libevdev-dev \
          libmbedtls-dev \
          libcurl4-openssl-dev \
          libegl1-mesa-dev \
          libpng-dev \
          qtbase5-private-dev \
          libxxf86vm-dev \
          x11proto-xinerama-dev
    - name: "Create build directory and run CMake"
      run: cmake -S . -B build -G "Unix Makefiles" -DLINUX_LOCAL_DEV=true
    - name: "Build Project" 
      run: cmake --build build --target all --config Release -- -j$(nproc)
    - name: Run make
      run: |
        cd build
        make
    - name: Copy Files
      run: cp -r ../Data/Sys/ ../Data/User/ ./Binaries
    - name: Make build portable
      run: touch ./Binaries/portable.txt
