name: Netplay V3 for Linux

on:
  push:
    branches: [ "bb" ]
  pull_request:
    branches: [ "bb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Install prerequisites"
      shell: bash
      run: |
        sudo dpkg --add-architecture amd64
        sudo apt update
        sudo apt install -y software-properties-common 
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt install -y gcc-11 g++-11
        sudo apt update
        sudo apt install \
        pkg-config \
        wget \
        libfuse2 \
        libao-dev \
        libasound2-dev \
        libavcodec-dev \
        libavformat-dev \
        libbluetooth-dev \
        libenet-dev \
        libgtk2.0-dev \
        liblzo2-dev \
        libminiupnpc-dev \
        libopenal-dev \
        libpulse-dev \
        libreadline-dev \
        libsfml-dev \
        libsoil-dev \
        libsoundtouch-dev \
        libswscale-dev \
        libusb-1.0-0-dev \
        libwebkit2gtk-4.0-dev \
        libxext-dev \
        libxrandr-dev \
        portaudio19-dev \
        zlib1g-dev \
        libudev-dev \
        libevdev-dev \
        libmbedtls-dev \
        libcurl4-openssl-dev \
        libegl1-mesa-dev \
        libpng-dev \
        libxxf86vm-dev \
        x11proto-xinerama-dev \
        xorg \ 
        openbox
    - name: "Create build directory and run CMake"
      run: cmake -S . -B build -G "Unix Makefiles" -DLINUX_LOCAL_DEV=true
    - name: "Build Project" 
      run: cmake --build build --target all --config Release -- -j$(nproc)
    - name: Run make
      run: |
        cd {{github.workspace}}/build
        make
    - name: Copy Files
      run: cp -r ../Data/Sys/ ../Data/User/ {{github.workspace}}/Binaries/
    - name: Make build portable
      run: touch {{github.workspace}}/Binaries/portable.txt
